### ISSUE TITLE
Integration with reticulate

### ISSUE THREAD

**Issue by statsmaths** [kbenoit/spacyr#23]
In  https://github.com/statsmaths/coreNLP/issues/1 I understood spacyr to be running over reticulate, but that doesn't seem to be the case at the moment. Are there plans to move towards  reticulate?

**Comment by kbenoit** [comment]
It looks like we have sorted out how to get the Python via Rcpp working even on operational systemly challenged systems, e.g. Windows. We're going to integrate this into the master branch asap and should no longer need **reticulate**. Stay tuned.

@amatsuo ...

**Comment by amatsuo** [comment]
@statsmaths We have a branch called dev_reticulate, which uses reticulate package instead of running via Rcpp. The branch does not use the nice features of reticulate such as revealing python methods in R. See Line 205 - 222 of the link below:
https://github.com/kbenoit/spacyr/blob/dev_reticulate/R/parse.R

We might be fully switching to the reticulate solution if we are convinced that it works flawlessly in Windows. We had so far limited success in using it in Windows (tested a while ago so maybe things have changed). It worked with Python 3.5 but not with 2.7. The windows implementation has been a headache for us and that's the reason why we tested out reticulate.

**Comment by kbenoit** [comment]
@statsmaths try installing from the new `master` branch, it should work now on any platform. 

🤞

**Comment by amatsuo** [comment]
We have switched to `reticulate` in the current version.
