### ISSUE TITLE
spacy_parse() does not accept quanteda corpus object

### ISSUE THREAD

**Issue by bachl** [kbenoit/spacyr#64]
The `spacy_parse()` function does not accept a quanteda corpus object as input despite saying so in the documentation:

> x	a character object, a quanteda corpus, or a TIF-compliant corpus data.frame (see https://github.com/ropensci/tif)

Example
```r
> require(quanteda); packageVersion("quanteda")
[1] ‘0.9.9.65’
> require(spacyr); packageVersion("spacyr")
Loading required package: spacyr
[1] ‘0.9.0’
> spacy_initialize(model = "en", python_executable = "/usr/local/bin/python3")
successfully initialized (spaCy , language model: en)
> spacy_parse(data_corpus_inaugural)
Error in UseMethod("spacy_parse") : 
  no applicable method for 'spacy_parse' applied to an object of class "c('corpus', 'list')"

**Comment by amatsuo** [comment]
Thank you for the feedback. 

The documentation is not correct. The current version of `spacyr` does not have the dependency on quanteda, and therefore we have removed the `spacy_parse.corpus()` method from the package. We will update the documentation in the next update.

If the issue is about not being able to use a quanteda's corpus object in spacy, please use the `quanteda::texts()` method that will convert a corpus object to a text vector with document names.

```
spacy_parse(quanteda::texts(data_corpus_inaugural))
```

**Comment by kbenoit** [comment]
I think I removed this code from quanteda because I had to since spacyr was not on cran yet. I can reenable it now that it is.

**Comment by methodds** [comment]
will this be reenabled for  [spacy 2.0](https://github.com/explosion/spaCy/releases/tag/v2.0.0)?

**Comment by kbenoit** [comment]
Solved in https://github.com/kbenoit/quanteda/pull/1059
