### ISSUE TITLE
find_spacy does not detect anaconda versions of Python

### ISSUE THREAD

**Issue by methodds** [kbenoit/spacyr#81]
Hi, 
I was wondering why `spacy_initialize` was not able to detect my Python 3 [anaconda](https://www.anaconda.com/download/) environment, which is a very common way to setup python nowadays.
I found `find_spacy()` and the corresponding code chunk 
````
  py_execs <- if (Sys.info()["sysname"] == "Windows") {
    system2("where", "python", stdout = TRUE)
  }
  else {
    c(system2("which", "-a python", stdout = TRUE), system2("which", 
      "-a python3", stdout = TRUE))
  }
````
This code chunk returns the "standard" locations for the system python environments:
`` "/usr/bin/python"  "/usr/bin/python3"``
It does however not return the main python version in use. I don't know how to do this in R, but in Python you can find the main environment with the following code chunk:

````python -c "import sys; print(sys.executable)"````
which returns the correct path for me:
````/home/cs/anaconda3/bin/python````

**Comment by kbenoit** [comment]
@methodds Having an additional Anaconda distribution of Python also drove @amatsuo and me slightly crazy as well. 

@amatsuo is there a way to get this working more easily?

**Comment by amatsuo** [comment]
@methodds 
The temporal solution is to spacify the python_executabile when initializing spacy

```R
spacy_initialize(python_executable = "/home/cs/anaconda3/bin/python")
```

More fundamentally, the issue is when `system2` or `system` is called, it does not source `~/.bash_profile`. Because of this, the output from `system2` is different than the output when you run the same command on the console. 

To resolve this, we can do something trickey like this in the package:

```R
system2("source", "~/.bash_profile; which -a python")
```

But, I'm not sure that this won't be a cause of other issues. If we come up with a better solution, we will implement it in the future version, but for the time being, please use the temporal solution above.

@kbenoit I can create a new option `source_bash_profile` (default = `FALSE`)  in `spacy_initialize`.  Do you think it a good idea?

**Comment by kbenoit** [comment]
Actually, it is a good idea, since we would want users to be able to specify environment variables in ~/.R/.Rprofile that could specify the `python_executable` as an option. Then we could change the signature for `spacy_initialize()` to:

```r
spacy_initialize(model = "en", python_executable = getOption("spacyr_python_executable"), ...)
```
and this could function similarly to how quanteda sets its options, e.g. 
https://github.com/kbenoit/quanteda/blob/master/R/zzz.R#L6
and 
https://github.com/kbenoit/quanteda/blob/master/R/quanteda_options.R

where the `quanteda_options(initialize = TRUE)` only resets options that are not already defined. So if a user set one in `.Rprofile` then it would not get reset when **quanteda** starts.

**Comment by amatsuo** [comment]
@methodds 
A new CRAN version of `spacyr` should have resolved this issue. 

Also, a new development version provides an additional way of specifying the location of spaCy-ready python.  If you want to try the feature, please install it with:
```{R}
devtools::install_github("kbenoit/spacyr", build_vignettes = FALSE)
```

**Comment by methodds** [comment]
awesome, thanks :)
